Update 02-Pull_Docker.yml

diff --git a/.github/workflows/02-Pull_Docker.yml b/.github/workflows/02-Pull_Docker.yml
--- a/.github/workflows/02-Pull_Docker.yml
+++ b/.github/workflows/02-Pull_Docker.yml
@@ -4,26 +4,26 @@ on:
   workflow_run:
         workflows: ['Push Docker Image']
         types: [completed]
-        branches:
-            - 'main'
 
 jobs:
-
-  pull_docker:
+  Docker-Build-Success:
+    runs-on: ubuntu-latest
+    if: ${{ github.event.workflow_run.conclusion == 'success' }}
+    steps:
+      - run: echo "Starting to pull Latest Docker Image"
+      - name: run the image
+        run: |
+          OUTPUT=$(docker run chphanisaisriram/mlops:ci_cd_v1)
+          echo "Score:"
+          echo "$OUTPUT"
+          if [[ `echo "$OUTPUT 0.5" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1;  fi
+          echo "test.py script executed Successfully."
+      
+  Docker-Build-Failed:
+    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - name: Log in to registry
-      uses: docker/login-action@v2
-      with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-    - name: pull Docker Image
-      run: docker image pull chphanisaisriram/mlops:ci_cd_v1
-    - name: run the image
-      run: |
-        OUTPUT=$(docker run chphanisaisriram/mlops:ci_cd_v1)
-        echo "Score:"
-        echo "$OUTPUT"
-        if [[ `echo "$OUTPUT 0.5" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1;  fi
-        echo "test.py script executed Successfully."
+    - name: fail the job
+      run: | 
+          echo "Workflow to build Docker file failed. So, Unable to pull the latest Docker file."
+          exit 1
