Update pull_docker_reusable.yml

diff --git a/.github/workflows/pull_docker_reusable.yml b/.github/workflows/pull_docker_reusable.yml
--- a/.github/workflows/pull_docker_reusable.yml
+++ b/.github/workflows/pull_docker_reusable.yml
@@ -6,7 +6,7 @@ jobs:
   Docker-Build-Success:
     runs-on: ubuntu-latest
     #Condition to check if the parent workflow is successflow
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
+    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
         #Pull the Docker image only if the Parent workflow got Succeeded
       - run: echo "Starting to pull Latest Docker Image"
@@ -18,12 +18,12 @@ jobs:
           if [[ `echo "$OUTPUT 0.35" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1;  fi
           echo "test.py script executed Successfully."
       
-  Docker-Build-Failed:
+  #Docker-Build-Failed:
     #Condition to check if the parent Workflow is failed.
-    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
-    runs-on: ubuntu-latest
-    steps:
-    - name: fail the job #Fail the Job since Parent Job is failed, since Docker image is not available in the repo.
-      run: | 
-          echo "Workflow to build Docker file failed. So, Unable to pull the latest Docker file."
-          exit 1
+    #if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+    #runs-on: ubuntu-latest
+    #steps:
+    #- name: fail the job #Fail the Job since Parent Job is failed, since Docker image is not available in the repo.
+    #  run: | 
+    #      echo "Workflow to build Docker file failed. So, Unable to pull the latest Docker file."
+    #      exit 1
